title: Linh Thai # your name (or website title) here
logo: "images/pro headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>
  <a href="https://www.linkedin.com/in/mlinhtthai/">LinkedIn</a> 
  <br>
  <a href="pdf/Resume_LinhThai.pdf" class="btn btn--info">Resume</a>
  <br>
  <a href="https://github.com/linhthai206">GitHub</a>  
 
  
theme: jekyll-theme-minimal
